spring:
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-description: Flyway Scripts
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    url: ${spring.datasource.url}
    out-of-order: true
    ignore-migration-patterns: '*:ignored'
    schemas: boots
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: "jdbc:postgresql://localhost:5432/desoccer"
    dbcp2:
      default-schema: boots
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    generate-ddl: true
    defer-datasource-initialization: false
  sql:
    init:
      platform: postgres
      mode: always
      continue-on-error: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

jwt:
  secret: qwepuisdhfaksdjflsdfn12321___**
  expiration: 6000000

